name: 🚀 Deploy to Dev-Innovation

on:
  pull_request:
    types: 
      - synchronize
      - opened
      - labeled

jobs:
  web-deploy:
    name: 🎉 Deploy
    if: contains(github.event.pull_request.labels.*.name, 'ready for review')
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.bgsandbox.com
        username: willelder@bgsandbox.com
        password: ${{ secrets.ftp_password }}
        port: 21
        local-dir: ./_site/
        server-dir: dev-innovation.bgsandbox.com/oam/

        
        exclude: |
          **/.DS_Store
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/assets/sass/**
          **/uswds/img/material-icons-deprecated/**
          **/uswds/img/material-icons/*
  lighthouse:
    name: 👀 Lighthouse Scan
    runs-on: ubuntu-latest
    needs: web-deploy
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@master
    - name: 👀 Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://www.dev-innovation.bgsandbox.com/oam/home.html, https://www.dev-innovation.bgsandbox.com/oam/views/about/about.html, https://www.dev-innovation.bgsandbox.com/oam/views/about/whoweare.html, https://www.dev-innovation.bgsandbox.com/oam/views/products/products.html, https://www.dev-innovation.bgsandbox.com/oam/views/products/product-submission.html, https://www.dev-innovation.bgsandbox.com/oam/views/training/training.html, https://www.dev-innovation.bgsandbox.com/oam/views/training/training.html, https://www.dev-innovation.bgsandbox.com/oam/views/news/news.html, https://www.dev-innovation.bgsandbox.com/oam/views/publications/publications.html'
        device: all  
        awsAccessKeyId: ${{ secrets.LIGHTHOUSE_CHECK_AWS_ACCESS_KEY_ID }}
        awsBucket: ${{ secrets.LIGHTHOUSE_CHECK_AWS_BUCKET }}
        awsRegion: ${{ secrets.LIGHTHOUSE_CHECK_AWS_REGION }}
        awsSecretAccessKey: ${{ secrets.LIGHTHOUSE_CHECK_AWS_SECRET_ACCESS_KEY }}
        gitAuthor: ${{ github.actor }}
        gitBranch: ${{ github.ref }}
        gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
        sha: ${{ github.sha }}
        slackWebhookUrl: ${{ secrets.LIGHTHOUSE_CHECK_WEBHOOK_URL }}